"""
src/sot_graph/analytics/bundle.py
Deterministic Fact Bundler for sot-graph.
Extracts structured codebase facts from sot.db into high-density Markdown artifacts
serving as Stage 1 inputs for LLM-assisted architectural report synthesis.
"""
from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Dict, Optional

from sot_graph.analytics.architecture import ArchitectureProfile
from sot_graph.analytics.diagnostics import AnalysisResult, analyze_graph
from sot_graph.analytics.graph import AnalyticsGraph
from sot_graph.db import Database

class ArchitectureBundler:
    """Extracts and writes structured architectural fact bundles from AnalyticsGraph."""

    def __init__(
        self,
        db: Optional[Database] = None,
        root_dir: str = ".",
        graph: Optional[AnalyticsGraph] = None,
    ):
        self.db = db
        self.root_dir = os.path.abspath(root_dir)
        if graph is not None:
            self.graph = graph
        elif db is not None:
            self.graph = AnalyticsGraph.from_database(db)
        else:
            raise ValueError("Either db or graph must be provided to ArchitectureBundler")
        self.analysis: AnalysisResult = analyze_graph(self.graph)
        self.profile: Optional[ArchitectureProfile] = self.analysis.architecture_profile

    def extract_bundle(self, output_dir: Optional[str] = None) -> Dict[str, str]:
        """
        Generate all 5 fact bundle artifacts and return a dictionary of {filename: content}.
        If output_dir is provided, writes files directly to disk.
        """
        if output_dir is None:
            output_dir = os.path.join(self.root_dir, ".sot", "bundle")

        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)

        bundle = {
            "01_module_inventory.md": self._generate_module_inventory(),
            "02_routing_endpoints.md": self._generate_routing_endpoints(),
            "03_workflows_states.md": self._generate_workflows_and_states(),
            "04_dependencies_violations.md": self._generate_dependencies_and_violations(),
            "05_system_metrics.json": self._generate_system_metrics_json(),
        }

        for filename, content in bundle.items():
            file_path = out_path / filename
            file_path.write_text(content, encoding="utf-8")

        return bundle

    def _generate_module_inventory(self) -> str:
        """Generate 01_module_inventory.md listing all functional modules and entities."""
        lines = [
            "# Fact Bundle 01: Functional Module Inventory & Feature Taxonomy",
            "> **Generated by sot-graph Architecture Bundler**",
            "",
            "## 1. Overview of Bounded Functional Modules",
            "",
        ]

        if not self.profile or not self.profile.functional_modules:
            lines.append("*(No structured functional modules discovered)*\n")
            return "\n".join(lines)

        lines.extend([
            "| Module Name | Category | Primary Responsibility | Core Entities / Models | Entrypoints / Handlers | Dependencies | Nodes / Files |",
            "| :--- | :--- | :--- | :--- | :--- | :--- | :-: |",
        ])

        for mod in self.profile.functional_modules:
            entities = ", ".join(f"`{e}`" for e in mod.core_entities[:4]) or "*None*"
            if len(mod.core_entities) > 4:
                entities += f" *(+{len(mod.core_entities)-4} more)*"

            entrypoints = ", ".join(f"`{ep}`" for ep in mod.entrypoints[:3]) or "*None*"
            if len(mod.entrypoints) > 3:
                entrypoints += f" *(+{len(mod.entrypoints)-3} more)*"

            deps = ", ".join(f"`{d}`" for d in mod.dependencies[:3]) or "*Standalone*"
            if len(mod.dependencies) > 3:
                deps += f" *(+{len(mod.dependencies)-3} more)*"

            lines.append(
                f"| **{mod.name}** | `{mod.category}` | {mod.responsibility} | {entities} | {entrypoints} | {deps} | {mod.node_count} / {mod.file_count} |"
            )

        lines.extend([
            "",
            "---",
            "",
            "## 2. Deep-Dive Per Module & File Inventory",
            "",
        ])

        for mod in self.profile.functional_modules:
            lines.append(f"### Module: `{mod.name}` ({mod.category})")
            lines.append(f"- **Primary Responsibility:** {mod.responsibility}")
            lines.append(f"- **Total Nodes:** {mod.node_count} | **Total Files:** {mod.file_count}")
            lines.append(f"- **Dependencies:** {', '.join(f'`{d}`' for d in mod.dependencies) or '*None*'}")
            
            if mod.core_entities:
                lines.append(f"- **Core Entities / Domain Models:** {', '.join(f'`{e}`' for e in mod.core_entities)}")
            if mod.entrypoints:
                lines.append(f"- **Entrypoints / Controllers / Routers:** {', '.join(f'`{ep}`' for ep in mod.entrypoints)}")
            
            if mod.sample_symbols:
                lines.append("- **Key Methods & Symbols:**")
                for sym in mod.sample_symbols[:10]:
                    lines.append(f"  - `{sym}`")

            if mod.internal_files:
                lines.append("- **Internal Source Files:**")
                for f in mod.internal_files[:15]:
                    lines.append(f"  - `{f}`")
                if len(mod.internal_files) > 15:
                    lines.append(f"  - *... and {len(mod.internal_files) - 15} additional files*")
            lines.append("")

        return "\n".join(lines)

    def _generate_routing_endpoints(self) -> str:
        """Generate 02_routing_endpoints.md detailing HTTP API, UI Pages, and Event Routes."""
        lines = [
            "# Fact Bundle 02: Routing Architecture & Endpoint Inventory",
            "> **Generated by sot-graph Architecture Bundler**",
            "",
        ]

        if not self.profile or not self.profile.routing_architecture:
            lines.append("*(No routing architecture discovered)*\n")
            return "\n".join(lines)

        ra = self.profile.routing_architecture
        lines.append(f"**Total Discovered Routes:** `{ra.total_routes}` ("
                     f"HTTP APIs: `{len(ra.http_routes)}`, "
                     f"UI Pages / Views: `{len(ra.ui_routes)}`, "
                     f"Event / Messaging: `{len(ra.event_routes)}`)\n")

        # 1. HTTP APIs
        lines.extend([
            "## 1. HTTP API Route Endpoints",
            "",
            "| Method | Endpoint / URI Pattern | Controller / Handler Function | Source Anchor (File:Line) | Auth / Guard | Target Layer |",
            "| :---: | :--- | :--- | :--- | :--- | :--- |",
        ])
        if ra.http_routes:
            for r in ra.http_routes:
                method = r.method or "ANY"
                auth = f"`{r.auth_guard}`" if r.auth_guard else "*Public / Default*"
                layer = r.target_layer or "API Layer"
                lines.append(
                    f"| `{method}` | `{r.path_or_pattern}` | `{r.handler}` | `{r.file_anchor}:{r.line}` | {auth} | `{layer}` |"
                )
        else:
            lines.append("| - | *No HTTP API endpoints found* | - | - | - | - |")
        lines.append("")

        # 2. UI Pages
        lines.extend([
            "## 2. UI Page & Navigation Routes",
            "",
            "| Page / Route Pattern | UI Component / View Class | Source Anchor (File:Line) | Target Layer |",
            "| :--- | :--- | :--- | :--- |",
        ])
        if ra.ui_routes:
            for r in ra.ui_routes:
                layer = r.target_layer or "Presentation"
                lines.append(
                    f"| `{r.path_or_pattern}` | `{r.handler}` | `{r.file_anchor}:{r.line}` | `{layer}` |"
                )
        else:
            lines.append("| *No UI page routes found* | - | - | - |")
        lines.append("")

        # 3. Event Busses & State Dispatches
        lines.extend([
            "## 3. Event Bus & State Dispatches",
            "",
            "| Event / State Pattern | Handler / Emitter Class | Source Anchor (File:Line) |",
            "| :--- | :--- | :--- |",
        ])
        if ra.event_routes:
            for r in ra.event_routes:
                lines.append(
                    f"| `{r.path_or_pattern}` | `{r.handler}` | `{r.file_anchor}:{r.line}` |"
                )
        else:
            lines.append("| *No event dispatches found* | - | - |")
        lines.append("")

        return "\n".join(lines)

    def _generate_workflows_and_states(self) -> str:
        """Generate 03_workflows_states.md discovering state machines, cron jobs, and background workers."""
        lines = [
            "# Fact Bundle 03: Workflows, State Machines & Background Automation",
            "> **Generated by sot-graph Architecture Bundler**",
            "",
            "## 1. Discovered State Machines & Lifecycle Enums",
            "",
        ]

        state_nodes = []
        cron_nodes = []
        service_nodes = []

        for _node_id, data in self.graph.nodes.items():
            label = str(data.get("label", ""))
            path = str(data.get("path", ""))
            kind = str(data.get("kind", ""))

            # Detect state machines / status fields
            if re.search(r"(state|status|stage|lifecycle|step|phase|tsc_state)", label, re.I) or \
               re.search(r"(state|status|workflow)", path, re.I):
                state_nodes.append((label, path, kind))

            # Detect cron jobs / scheduled tasks
            if re.search(r"(cron|schedule|periodic|background|worker|interval|reminder|auto_assign)", label, re.I) or \
               re.search(r"(cron|task|job)", path, re.I):
                cron_nodes.append((label, path, kind))

            # Detect external services & connectors
            if re.search(r"(connector|client|integration|api_service|gateway|voffice|bccs|bcel|unipay|umoney|ilp)", label, re.I) or \
               re.search(r"(integration|connector|client)", path, re.I):
                service_nodes.append((label, path, kind))

        if state_nodes:
            lines.extend([
                "| State / Workflow Node | Entity / File Path | Kind |",
                "| :--- | :--- | :--- |",
            ])
            for lbl, p, k in state_nodes[:25]:
                lines.append(f"| `{lbl}` | `{p}` | `{k}` |")
            if len(state_nodes) > 25:
                lines.append(f"| *... and {len(state_nodes)-25} more workflow symbols* | - | - |")
        else:
            lines.append("*(No explicit state machine symbols detected)*")
        lines.append("")

        lines.extend([
            "## 2. Background Workers, Cron Jobs & Scheduled Tasks",
            "",
        ])
        if cron_nodes:
            lines.extend([
                "| Worker / Cron Job Symbol | File Path | Kind |",
                "| :--- | :--- | :--- |",
            ])
            for lbl, p, k in cron_nodes[:25]:
                lines.append(f"| `{lbl}` | `{p}` | `{k}` |")
            if len(cron_nodes) > 25:
                lines.append(f"| *... and {len(cron_nodes)-25} more background tasks* | - | - |")
        else:
            lines.append("*(No explicit background cron workers detected)*")
        lines.append("")

        lines.extend([
            "## 3. Integration Connectors & External Gateway Handlers",
            "",
        ])
        if service_nodes:
            lines.extend([
                "| Connector / Service Symbol | File Path | Kind |",
                "| :--- | :--- | :--- |",
            ])
            for lbl, p, k in service_nodes[:25]:
                lines.append(f"| `{lbl}` | `{p}` | `{k}` |")
            if len(service_nodes) > 25:
                lines.append(f"| *... and {len(service_nodes)-25} more connector symbols* | - | - |")
        else:
            lines.append("*(No explicit external connectors detected)*")
        lines.append("")

        return "\n".join(lines)

    def _generate_dependencies_and_violations(self) -> str:
        """Generate 04_dependencies_violations.md capturing God nodes, blast radius, and layer violations."""
        lines = [
            "# Fact Bundle 04: Inter-Module Dependencies & Architectural Violations",
            "> **Generated by sot-graph Architecture Bundler**",
            "",
            "## 1. Architectural Violations (Layer Bypasses & Inverted Dependencies)",
            "",
        ]

        violations = self.profile.violations if self.profile else []
        if violations:
            lines.extend([
                "| Severity | Violation Type | Source Symbol & Path | Target Symbol & Path | Description & Recommendation |",
                "| :---: | :--- | :--- | :--- | :--- |",
            ])
            for v in violations:
                sev = f"**{v.severity}**"
                src = f"`{v.source_node}`<br/>*({v.source_path})*" if v.source_path else f"`{v.source_node}`"
                tgt = f"`{v.target_node}`<br/>*({v.target_path})*" if v.target_path else f"`{v.target_node}`"
                lines.append(
                    f"| {sev} | `{v.violation_type}` | {src} | {tgt} | {v.description}<br/>**Fix:** {v.recommendation} |"
                )
        else:
            lines.append("`ZERO_VIOLATIONS`: Architecture strictly conforms to unidirectional layer boundaries.\n")
        lines.append("")

        # 2. God Nodes / High Blast Radius
        lines.extend([
            "## 2. High Blast-Radius Entities (God Nodes)",
            "",
            "| Entity / Symbol | In-Degree (Incoming Calls) | Out-Degree (Outgoing Calls) | Total Degree | Blast Radius Risk |",
            "| :--- | :---: | :---: | :---: | :--- |",
        ])
        god_nodes = self.analysis.god_nodes
        if god_nodes:
            for gn in god_nodes[:15]:
                risk = "**CRITICAL**" if gn.total_degree > 30 else ("**HIGH**" if gn.total_degree > 15 else "MEDIUM")
                lines.append(
                    f"| `{gn.node_id}` | `{gn.in_degree}` | `{gn.out_degree}` | `{gn.total_degree}` | {risk} |"
                )
        else:
            lines.append("| *(No excessive God Nodes detected)* | - | - | - | - |")
        lines.append("")

        return "\n".join(lines)

    def _generate_system_metrics_json(self) -> str:
        """Generate 05_system_metrics.json summarizing quantitative metrics."""
        m = self.analysis.metrics
        prof = self.profile

        data = {
            "project_root": self.root_dir,
            "pattern_name": prof.pattern_name if prof else "Modular Layered Architecture",
            "primary_language": prof.primary_language if prof else "General",
            "framework_hints": prof.framework_hints if prof else [],
            "modularity_score_q": round(m.modularity, 4),
            "modularity_verdict": prof.modularity_verdict if prof else "N/A",
            "total_nodes": m.node_count,
            "total_edges": m.edge_count,
            "total_files": m.file_count,
            "total_symbols": m.symbol_count,
            "graph_density": round(m.density, 6),
            "average_degree": round(m.avg_degree, 2),
            "total_communities": m.community_count,
            "total_violations": len(prof.violations) if prof else 0,
            "total_routes": prof.routing_architecture.total_routes if prof and prof.routing_architecture else 0,
            "total_functional_modules": len(prof.functional_modules) if prof else 0,
        }
        return json.dumps(data, indent=2)
